common: &common
  adapter: postgresql
  username: postgres
  password:

development:
  <<: *common
  database: ofc2_development

test:
  <<: *common
  database: ofc2_test

production:
  <<: *common
  database: ofc2_production
